social:
  facebook_url: 'https://www.facebook.com/PoclainHydraulics'
  linkedin_url: 'https://www.linkedin.com/company/poclain-hydraulics'
  youtube_url: 'https://www.youtube.com/user/PoclainHydraulicsTV'
langcode: fr
