features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
  path: ''
favicon:
  use_default: 0
  path: themes/custom/addidrive/images/favicon.png
  mimetype: image/png
langcode: fr
