export:
  folder: custom
langcode: fr
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
popup_info:
  value: "<p>Les cookies assurent le bon fonctionnement de nos services. En utilisant ces derniers, vous acceptez l’utilisation des cookies.</p>\r\n"
  format: tf_rich_text
popup_agreed:
  value: "<h2>Thank you for accepting cookies</h2>\r\n\r\n<p>You can now hide this message or find out more about cookies.</p>\r\n"
  format: tf_rich_text
domain: ''
popup_enabled: true
popup_clicking_confirmation: false
popup_position: false
popup_agree_button_message: OK
popup_disagree_button_message: 'En savoir plus'
popup_agreed_enabled: false
popup_hide_agreed: false
popup_find_more_button_message: 'More info'
popup_hide_button_message: Hide
popup_link: 'internal:/cookies'
popup_link_new_window: true
popup_height: null
popup_width: 100%
popup_delay: 1
popup_bg_hex: 5986ab
popup_text_hex: ffffff
domains_option: 1
domains_list: ''
