custom:
  -
    path: /
  -
    path: /actualites
  -
    path: /contact
  -
    path: /la-presse
  -
    path: /cookies
entity_types:
  node_type:
    ct_news:
      index: 1
      priority: 0.5
    ct_page:
      index: 1
      priority: 0.5
    ct_testimonial:
      index: 1
      priority: 0.5
settings:
  max_links: 2000
  cron_generate: true
  remove_duplicates: true
  batch_process_limit: 1500
langcode: fr
